### ISSUE TITLE
python libs

### ISSUE THREAD

**Issue by blackout314** [hareevs/barcode#1]
apt-get install python-epr [OK]

but i've this error

```
raceback (most recent call last):
  File "read.py", line 3, in <module>
    import barcode
  File "/home/blackout/GIT/barcode/barcode/__init__.py", line 1, in <module>
    from .reader import Reader, WebReader
  File "/home/blackout/GIT/barcode/barcode/reader.py", line 4, in <module>
    from urllib3 import Request, urlopen
ImportError: cannot import name Request
```

**Comment by blackout314** [comment]
lib to install?

**Comment by ViktorStiskala** [comment]
Hello, this module is tested only on Python 3 and it seems you are using Python 2.x.
Please try running in Python 3.3+.

Also it seems you have changed import statement on reader.py: line 4. The previous one was correct.

**Comment by blackout314** [comment]
Ok thank you so much for your answer
